version: '3.8'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
        depends_on:
            - db
        networks:
            - lamp-network
        # In this way, I am fixing Windows file permission issues
        environment:
            - APACHE_RUN_USER=www-data
            - APACHE_RUN_GROUP=www-data

    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - lamp-network
        # Windows-specific MySQL config
        command: --default-authentication-plugin=mysql_native_password

networks:
    lamp-network:
        driver: bridge

volumes:
    mysql-data:
