version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: portfolio
        volumes:
            - ./:/var/www
        working_dir: /var/www
        networks:
            - laravel

    webserver:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: mysql:5.7
        container_name: db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel

volumes:
    dbdata:

networks:
    laravel:
